# Generated by Django 5.0.10 on 2024-12-24 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('authority', models.CharField(default='', max_length=255, unique=True, verbose_name='Authority')),
                ('nuid', models.CharField(default='', max_length=7, verbose_name='NUID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='First Name')),
                ('middle', models.CharField(blank=True, default='', max_length=255, verbose_name='Middle Name')),
                ('lastname', models.CharField(blank=True, default='', max_length=255, verbose_name='Last Name')),
                ('wrk_class', models.CharField(blank=True, default='', max_length=255, verbose_name='Workforce Class')),
                ('status', models.CharField(blank=True, default='', max_length=255, verbose_name='Status')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Company Name')),
                ('start_date', models.DateField(blank=True, default=datetime.date(1900, 1, 1), verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=datetime.date(1900, 1, 1), verbose_name='Projected End Date')),
                ('region_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Region Code')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='Region Name')),
                ('entity', models.CharField(blank=True, default='', max_length=255, verbose_name='Entity Name')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='Department Name')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Location Description')),
                ('job_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Job Title')),
                ('job_position', models.CharField(blank=True, default='', max_length=255, verbose_name='Job Position')),
                ('job_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Job Code')),
                ('cost_center', models.CharField(blank=True, default='', max_length=255, verbose_name='Cost Center Name')),
                ('job_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Job Description')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Business Address')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='KP email address')),
                ('site_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Site ID')),
                ('manager', models.CharField(blank=True, default='', max_length=255, verbose_name='KP Manager')),
                ('institution', models.CharField(blank=True, default='', max_length=255, verbose_name='Institution')),
                ('dor', models.CharField(blank=True, default='', max_length=255, verbose_name='DOR Status')),
                ('is_oncologist', models.BooleanField(blank=True, default=False, verbose_name='Is DOR Oncologist?')),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authorities',
                'db_table': 'testing_authorities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=128, verbose_name='Test')),
            ],
            options={
                'db_table': 'testing_test',
                'managed': True,
            },
        ),
    ]
