[[build.env]]
name = "DISABLE_COLLECTSTATIC"
value = "1"

[[build.env]]
name =  "GOOGLE_RUNTIME_VERSION"
value = "3.12.10"

[[build.env]]
name = "GOOGLE_ENTRYPOINT"
value = "gunicorn config.wsgi:application --bind \"0.0.0.0:$PORT\""
